#!/bin/bash

# Author: Jorge Garcia Bermejo

if [ "$#" -ne 1 ]; then
	echo -e "\n[!] You can only pass one argument to this script"
	exit 1
fi

filename=$1
default_text=$(
	cat <<E0F
#!/bin/bash

# Author: Jorge Garcia Bermejo

#Colors
greenColor="\e[0;32m\033[1m"
endColor="\033[0m\e[0m"
redColor="\e[0;31m\033[1m"
blueColor="\e[0;34m\033[1m"
yellowColor="\e[0;33m\033[1m"
purpleColor="\e[0;35m\033[1m"
turquoiseColor="\e[0;36m\033[1m"
grayColor="\e[0;37m\033[1m"

function ctrl_c() {
        echo -e "\n\n\${redColor}[!]\${endColor} Exiting..."
        exit 1
}

# Ctrl+c to trap to abort program at any point
trap ctrl_c INT
E0F
)

echo -e -E "$default_text" >"$filename"
